version: '3.8'

services:
 nginx:
   image: nginx:latest
   ports:
    - 80:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./src:/var/www/html
   depends_on:
    - php

 php:
  build: ./php
  volumes:
   - ./src:/var/www/html
  depends_on:
   - mysql

 mysql:
  image: mysql:latest
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  ports:
    - 3309:3306
  volumes:
   - db-data:/var/lib/mysql
  environment:
   MYSQL_DATABASE: ${DB_NAME}
   MYSQL_USER: ${DB_USER}
   MYSQL_PASSWORD: ${DB_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   TZ: 'Asia/Tokyo'

 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  environment:
   PMA_HOST: mysql
  ports:
   - 8080:80
  depends_on:
   - mysql

volumes:
 db-data:
